### ISSUE TITLE
About SWE-bench Lite-S

### ISSUE THREAD

**Issue by pengfeigao1** [OpenAutoCoder/Agentless#1]
Hi @brutalsavage , this is a very impressive work. Do you have the plan to open source SWE-bench Lite-S?

**Comment by brutalsavage** [comment]
Hi @pengfeigao1, we do plan to open-source SWE-bench lite-S! currently we are working on finalizing some of the classifications, will let you know as soon as it is released.

**Comment by brutalsavage** [comment]
Hi @pengfeigao1 

We just released our classifications on SWE-bench-lite, you can check it out here: https://github.com/OpenAutoCoder/Agentless/tree/main/classification
