### ISSUE TITLE
Reproducing SWE-bench-verified results

### ISSUE THREAD

**Issue by FloridSleeves** [OpenAutoCoder/Agentless#27]
Hi,

I'm working on reproducing the Agentless results on SWE-bench-verified. According to [this report](https://openai.com/index/introducing-swe-bench-verified/), the expected result is 33.2%. However, I'm only achieving around 24.6% in my experiments. Could you please validate my experiment settings? I'm using top_n_file=3, running the localization twice, and generating 21 patches for each run.

Also, do you plan to add the Agentless results to the SWE-bench-verified benchmarks later?

Thank you!

**Comment by brutalsavage** [comment]
Hi,

We did not run agentless on SWE-bench-verified, it is done independently by the OpenAI team, so I am not 100% sure about their experimental settings. But from what you described it seems like you are using our default setting in the agentless paper which should be fine. My guess could be some variance recently with GPT-4o performance (it seems to be slightly worse not? but I am not totally sure about this) 

>Also, do you plan to add the Agentless results to the SWE-bench-verified benchmarks later?

Yes we hope to continue improving agentless and submit to the SWE-bench-verified benchmark later

Thanks

**Comment by FloridSleeves** [comment]
I see. Thank you for your response!
