### ISSUE TITLE
ModuleNotFoundError: No module named 'agentless.fl'

### ISSUE THREAD

**Issue by minhnhatle104** [OpenAutoCoder/Agentless#36]
Dear team, currently I tried to set up and run Agentless project in my local laptop.
But I faced the issue that **ModuleNotFoundError: No module named 'agentless.fl'**

Here is the log:
DELL@nhatminhdell MINGW64 /d/nau/Master/Term/Winter-2025/projects/Agentless (main)
$ conda activate agentless
(agentless)
DELL@nhatminhdell MINGW64 /d/nau/Master/Term/Winter-2025/projects/Agentless (main)
$ which python
/c/Users/DELL/anaconda3/envs/agentless/python
(agentless)
DELL@nhatminhdell MINGW64 /d/nau/Master/Term/Winter-2025/projects/Agentless (main)
$ echo $PYTHONPATH
C:\Users\DELL\anaconda3\envs\agentless
(agentless)
DELL@nhatminhdell MINGW64 /d/nau/Master/Term/Winter-2025/projects/Agentless (main)
$ export PYTHONPATH=$PYTHONPATH:$(pwd)
(agentless)
DELL@nhatminhdell MINGW64 /d/nau/Master/Term/Winter-2025/projects/Agentless (main)
$ echo $PYTHONPATH
C:\Users\DELL\anaconda3\envs\agentless:/d/nau/Master/Term/Winter-2025/projects/Agentless
(agentless)
DELL@nhatminhdell MINGW64 /d/nau/Master/Term/Winter-2025/projects/Agentless (main)
$ python agentless/fl/localize.py --file_level --related_level --fine_grain_line_level \ --output_folder results/location --top_n 3 \ --compress \ --context_window=10
Traceback (most recent call last):
  File "D:\nau\Master\Term\Winter-2025\projects\Agentless\agentless\fl\localize.py", line 9, in <module>
    from agentless.fl.FL import LLMFL
ModuleNotFoundError: No module named 'agentless.fl'
(agentless)

Could you please see the issue and show me the correct way ?

**Comment by minhnhatle104** [comment]
For your reference, I attached my images. I am using laptop DELL ( Windows 11):
![Screenshot 2024-10-23 025743](https://github.com/user-attachments/assets/ce321998-ea29-4af8-81dd-5065950585b0)
![Screenshot 2024-10-23 025833](https://github.com/user-attachments/assets/4cb878df-a7e1-4533-980d-905bc8143234)
![Screenshot 2024-10-23 025935](https://github.com/user-attachments/assets/5cd46d86-f553-443c-965a-c9d8412d51dc)

**Comment by minhnhatle104** [comment]
For this error, I can solve it by setting PYTHONPATH point to the path where agentless folder is located.
For example, in my case, agentless folder is stored in Agentless project ( folder) so it would be:
export PYTHONPATH=/d/nau/playground/Winter-2025/projects/Agentless

**Comment by zhimin-z** [comment]
Here is what I have:
```
(agentless) PS C:\Users\zhimi\OneDrive\Documents\GitHub\Agentless> $env:PYTHONPATH="C:\Users\zhimi\OneDrive\Documents\GitHub\Agentless"                                                     
(agentless) PS C:\Users\zhimi\OneDrive\Documents\GitHub\Agentless> python agentless/fl/localize.py --file_level --output_folder results/swe-bench-lite/file_level --num_threads 10 --skip_existing
Traceback (most recent call last):
  File "C:\Users\zhimi\OneDrive\Documents\GitHub\Agentless\agentless\fl\localize.py", line 10, in <module>
    from agentless.fl.FL import LLMFL
ModuleNotFoundError: No module named 'agentless.fl'
(agentless) PS C:\Users\zhimi\OneDrive\Documents\GitHub\Agentless> $env:PYTHONPATH = "$env:PYTHONPATH;$(Get-Location)"                                                                      
(agentless) PS C:\Users\zhimi\OneDrive\Documents\GitHub\Agentless> python agentless/fl/localize.py --file_level --output_folder results/swe-bench-lite/file_level --num_threads 10 --skip_existing
Traceback (most recent call last):
  File "C:\Users\zhimi\OneDrive\Documents\GitHub\Agentless\agentless\fl\localize.py", line 10, in <module>
    from agentless.fl.FL import LLMFL
ModuleNotFoundError: No module named 'agentless.fl'
```
