### ISSUE TITLE
Regression test over PASS_TO_PASS cases in SWE-bench?

### ISSUE THREAD

**Issue by Hodge931** [OpenAutoCoder/Agentless#38]
By this line: https://github.com/OpenAutoCoder/Agentless/blob/main/agentless/test/run_tests.py#L548, I guess the regression tests are using the PASS_TO_PASS testcases in the original dataset to do the filtering?

**Comment by brutalsavage** [comment]
Hi @Hodge931 We **do not** use any of the PASS_TO_PASS testcases, we directly obtained all the passing tests in the original repository and then use LLM to select the list of regression tests. For more detail you can see the detailed [README](https://github.com/brutalsavage/Agentless/blob/main/README_swebench.md)

**Comment by Mizersy** [comment]
> obtained all the passing tests in the original repository

But this is exactly the way SWE-bench team obtained PASS_TO_PASS testcases?

**Comment by bamps53** [comment]
@brutalsavage 

But in this line, the swebench function uses test_patch from the instance object, and it seems to return only tests related to test_patch.
https://github.com/brutalsavage/Agentless/blob/59dc4b75e8590bc821867791de76350515ab38e8/agentless/test/run_tests.py#L275

I'm not familiar with swebench rules, but is it acceptable to use test_patch to filter tests? (In my opinion, it seems unrealistic to assume that only related tests can be obtained this way.)
